# Use a Python slim image suitable for Google Cloud environment
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy only the requirements file to avoid unnecessary rebuilds
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . .

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_ENV=development
ENV FLASK_APP=run.py
ENV FLASK_RUN_HOST=0.0.0.0

# Command to run the Flask application
CMD ["flask", "run", "--host=0.0.0.0"]
